version: "3.8"

services:
  web:
    build:
      context: .
      network: host #Definindo o HOST ps: Não instala as dependencias
    command: python manage.py runserver 0.0.0.0:8000 #Comando para inicar a aplicação
    image: pystore
    container_name: e-commerce
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
